# Generated by Django 4.2.5 on 2023-09-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
